### ISSUE TITLE
Stream Key

### ISSUE THREAD

**Issue by dobyvillanueva** [MissiaL/hikvision-client#12]
Hi,

Thank you for this API. Do you have an option for encrypted streams? I could not find where to input my stream key.

Thanks.

**Comment by MissiaL** [comment]
@dobyvillanueva Hi!
Could you explain what is encrypted streams?

**Comment by dobyvillanueva** [comment]
Hi @MissiaL 

I mean how do I input this encryption key in the API.

![image](https://user-images.githubusercontent.com/12248506/63711715-a3b4be80-c86e-11e9-9976-f51636b3b446.png)

Thanks :)
