### ISSUE TITLE
[Question] List of available dynamic methods?

### ISSUE THREAD

**Issue by msunjic98** [MissiaL/hikvision-client#13]
Hello, first, thank you for a great python client for Hikvision.

This is more a generic question for Hikvision than your client. I see that you made the client dynamic to use existing Hikvision calls/methods. I'm wondering, is there a list for all available hikvision methods that I can call with your library?

Thanks.
Best regards.

**Comment by msunjic98** [comment]
Okay, little bit of googling and I figured out you're using Hikvision's ISAPI, so I can close this.
Also, you could add the link to the documentation to README.md so other people can find it easier.
Nice library again :)
ftp://hdd.n-soft.net/Drivers/Camera/HIKVISION%20DS-2CD2512F/EN/Development%20Tools/ISAPI/ISAPI%20IPMD%20Service.pdf - link to documentation

**Comment by MissiaL** [comment]
I wanted to share with you the documentation of Hikvision, but you have already found it :-)

**Comment by msunjic98** [comment]
Yeah, even though I don't understand why some requests return 400 Bad Request or 403 Forbidden. Maybe they need Hikvision-CGI enabled on camera?

**Comment by MissiaL** [comment]
I have not tested all requests for Hikvision. Show your sample request

**Comment by msunjic98** [comment]
Forgot to comment back, my bad, I was adding System/ prefix to some of the routes, it looks like all works correctly. Thanks 👍
