### ISSUE TITLE
Bad quality picture

### ISSUE THREAD

**Issue by AndrewMarines** [MissiaL/hikvision-client#32]
Hello there.
I have an hard time getting an high quality picture from my Full HD digital camera. Even if i select the main stream [301] it gives me a picture in a resolution that is less than HD(something like 576x...). 

Watching from the website that explains how http picture works i found out even
`http://<user>:<password@192.168.0.xxx/ISAPI/Streaming/channels/301/picture` gives me the same quality as the library.
But if i try changing the last part as it follows here:
`http://<user>:<password@192.168.0.xxx/ISAPI/Streaming/channels/101/picture?videoResolutionWidth=1920&videoResolutionHeight=1080`
I can get the maximum resolution for the picture!
Didn't find anything on the api guide to do this. Did i miss this or? If not, can we change the code to let us do that?

**Comment by MissiaL** [comment]
@AndrewMarines Still relevant?

**Comment by AndrewMarines** [comment]
Nope, to anyone who could have this issue, watch the referenced issue. It's resolved there. Thank you again
